webscrapes:
  dm_url: 'https://deepmind.com/api/search/?content_type=research&filters=%7B%22collection%22:%5B%22Publications%22%5D%7D&page={t}&pagelen=21&q=&sort=relevance'
  n_pages: 40
  oai_url: "https://openai.com/papers/"
min_count: 700
topic_filter:
  presence_threshold: 0
  prevalence_threshold: 0.1
expansion_dict:
  cs.AI: 2
  cs.NE: 2
  cs.LG: 1
  stat.ML: 1
case_categories:
  - ["cs.CY",False] 
  - ["cs.CL",False]